### ISSUE TITLE
About the socks5 proxy service supplied by this project.

### ISSUE THREAD

**Issue by hongyi-zhao** [Hagb/docker-easyconnect#12]
Hi,

I noticed this project and it seems very interesting. As you have told in the description for this project: Let the non-free proxy software EasyConnect developed by Sangfor runs in docker cnotainer and provides a socks5 proxy service. I just want to know how you can convert a VPN service to a socks5 service. I inspected a little the [danted.conf](https://github.com/Hagb/docker-easyconnect/blob/master/docker-root/etc/danted.conf) configuration file used in this project. But I still not so clear on the working mechanism. Could you please kindly give me some more explanations/hints?

Regards,
HY

**Comment by Hagb** [comment]
Hi.
[`danted.conf`](https://github.com/Hagb/docker-easyconnect/blob/master/docker-root/etc/danted.conf) is the configuration file of [dante server](https://www.inet.no/dante/) which converts the VPN service to a socks5 service.
In this project, the following command is used to run dante server:
https://github.com/Hagb/docker-easyconnect/blob/ee0ee65fd2039b9a706ea7394258b343b77839d0/docker-root/usr/local/bin/start.sh#L18

**Comment by hongyi-zhao** [comment]
Can this be done by other tools, say, [haproxy](http://www.haproxy.org/), [transocks](https://github.com/cybozu-go/transocks), iptables, and so on?

**Comment by Hagb** [comment]
Other tools can also be used to do that.

For example, ip forwarding is set in (but I didn't mention it in document):
https://github.com/Hagb/docker-easyconnect/blob/ee0ee65fd2039b9a706ea7394258b343b77839d0/docker-root/usr/local/bin/start.sh#L30
and we can use (assume that the ip of EasyConnect container is `172.17.0.2` and mtu is `4800`)
``` shell
sudo ip route add 10.0.0.0/8 via 172.17.0.2 mtu 4800
```
so that the connection to `10.0.0.0/8` will go through EasyConnect.

Sorry for my poor English :-)

**Comment by hongyi-zhao** [comment]
Thanks a lot for your notes and explanations.
